/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CooperativaAhorro;

import view.Main;
import model.MainModel;
import controller.MainController;

public class App {
    private Main main;
    public String getInit() {
        return "Init project...";
    }

    public static void main(String[] args) {
        System.out.println(new App().getInit());
        MainModel model = new MainModel();
        Main view = new Main();
        
        MainController controller = new MainController(model, view);
        controller.init();
        view.setVisible(true);
    }
}
